version: '3.8'

services:
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: ${RESTART_POLICY}
    environment:
      - NODE_ENV=${NODE_ENV}
      - TRIGGER_API_URL=${TRIGGER_API_URL}
      - TRIGGER_API_KEY=${TRIGGER_API_KEY}
      - TRIGGER_WORKER_TOKEN=${TRIGGER_WORKER_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
      - COORDINATOR_HOST=${COORDINATOR_HOST}
      - COORDINATOR_PORT=${COORDINATOR_PORT}
      - REGISTRY_HOST=${REGISTRY_HOST}
      - REGISTRY_NAMESPACE=${REGISTRY_NAMESPACE}
      - MANAGED_WORKER_SECRET=${MANAGED_WORKER_SECRET}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - webapp
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - webapp

  redis:
    image: redis:${REDIS_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    volumes:
      - redis-data:/data
    ports:
      - "6390:6379"
    networks:
      - webapp

volumes:
  postgres-data:
  redis-data:

networks:
  webapp:
    driver: bridge 