version: '3.8'

services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: ${RESTART_POLICY}
    ports:
      - "${HTTP_SERVER_PORT}:${HTTP_SERVER_PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
      - TRIGGER_API_URL=${TRIGGER_API_URL}
      - TRIGGER_API_KEY=${TRIGGER_API_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - MAGIC_LINK_SECRET=${MAGIC_LINK_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - webapp
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:${POSTGRES_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - webapp

  redis:
    image: redis:${REDIS_IMAGE_TAG}
    restart: ${RESTART_POLICY}
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - webapp

volumes:
  postgres-data:
  redis-data:

networks:
  webapp:
    driver: bridge 